/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.s3m.launcher.Server.Model;

public class AssistantCard {
    private Assistant type;
    private int value;
    private int movement;

    public AssistantCard(Assistant type, int value, int movement) {
        this.type = type;
        this.value = value;
        this.movement = movement;
    }

    private Assistant getType() {
        return type;
    }

    private int getValue() {
        return value;
    }

    private int getMovement() {
        return movement;
    }
}