/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.s3m.launcher.Server.Model;

import java.util.*;

public class AssistantDeck implements Deck {
    private ArrayList<AssistantCard> cardList = new ArrayList<>();
    //ArrayList<Assistant> assistants =  new ArrayList<>(Arrays.asList(EAGLE, DOG, ELEPHANT, CAT, CHEETAH, LIZARD, OCTOPUS, OSTRICH, TURTLE, FOX));

    public AssistantDeck(){

    }

    @Override
    public void shuffle() {

    }
    @Override
    public void draw() {
    }



}