/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.s3m.launcher.Server.Model;

public abstract class CharacterCard {
    private int cost;

    public CharacterCard(int cost) {
        this.cost = cost;
    }

    public void activateEffect(){}

    private int getCost() {
        return cost;
    }

    private void setCost(int cost) {
        this.cost = cost;
    }
}