/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.s3m.launcher.Server.Model;

public class CharacterDeck implements Deck {
    @Override
    public void shuffle() {
    }
    @Override
    public void draw() {
    }
}