/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package it.polimi.ingsw.s3m.launcher.Server.Model;

import java.util.*;
import java.time.*;

public class CharacterCard {
    private String type;
    private int cost;

    public CharacterCard(String type, int cost) {
        this.type = type;
        this.cost = cost;
    }

    private String getType() {
        return type;
    }

    private int getCost() {
        return cost;
    }

    private void setType(String type) {
        this.type = type;
    }

    private void setCost(int cost) {
        this.cost = cost;
    }

    public void activateEffect() {
    }
}